spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} # environment variable
  datasource:
    url: ${datasource-url} # URL of Postgres in Azure
    username: ${datasource-username} # admin username i post
    password: ${datasource-password} # password of admin in post
  jpa:
    hibernate:
      ddl-auto: none # Turn off DDL
